version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:80"
  
  server:
    env_file:
      - ./server/.env
    build: ./server
    ports:
      - "5000:5000"
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"